insert into clients values (1, 'Alexandr', 'Kushmanov');
insert into clients values (2, 'Petr', 'Petrov');
insert into clients values (3, 'Ivan', 'Ivanov');
insert into clients values (4, 'Stepan', 'Stepanov');
insert into clients values (5, 'Roman', 'Romanov');
insert into clients values (6, 'Alexey', 'Alexeev');
insert into clients values (7, 'Sergey', 'Sergeev');
insert into clients values (8, 'Semen', 'Semenov');
insert into clients values (9, 'Artem', 'Artemov');
insert into clients values (10, 'Bogdan', 'Bogdanov');
insert into clients values (11, 'Anton', 'Antonov');
insert into clients values (12, 'Miron', 'Mironov');

insert into banks values (1, 'PRIVATBANK');
insert into banks values (2, 'ALFABANK');
insert into banks values (3, 'OSCHADBANK');
insert into banks values (4, 'UKRGAZBANK');
insert into banks values (5, 'PUMB');
insert into banks values (6, 'KREDOBANK');
insert into banks values (7, 'MEGABANK');
insert into banks values (8, 'TASKOMBANK');
insert into banks values (9, 'MONOBANK');
insert into banks values (10, 'OTPBANK');
insert into banks values (11, 'KONKORD');

insert into clients_banks values (1, 1);
insert into clients_banks values (1, 7);
insert into clients_banks values (1, 9);
insert into clients_banks values (2, 2);
insert into clients_banks values (3, 3);
insert into clients_banks values (4, 4);
insert into clients_banks values (5, 1);
insert into clients_banks values (5, 2);
insert into clients_banks values (5, 3);
insert into clients_banks values (6, 9);
insert into clients_banks values (6, 10);
insert into clients_banks values (7, 11);
insert into clients_banks values (8, 6);
insert into clients_banks values (8, 7);
insert into clients_banks values (9, 8);
insert into clients_banks values (10, 6);
insert into clients_banks values (11, 10);
insert into clients_banks values (11, 11);
insert into clients_banks values (12, 5);